apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base-app
spec:
  destination:
    namespace: base
    server: https://kubernetes.default.svc
  project: default
  source:
    path: base/apps
    repoURL: https://github.com/nleea/argo-projects.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
